export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_SERVICECENTERS_SUCCESS = "FETCH_SERVICECENTERS_SUCCESS";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
